// This file is normally auto-generated by Lovable Cloud. We have replaced it
// to point at the LEGACY Supabase project (mfcdlifjxxdrekzdatfb) used by the
// older apps so that data is shared across projects.
//
// IMPORTANT: do not let Cloud regenerate this file pointing to the empty
// new Cloud database — if it ever does, restore the values below.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://mfcdlifjxxdrekzdatfb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1mY2RsaWZqeHhkcmVremRhdGZiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyMTg0MTMsImV4cCI6MjA1OTc5NDQxM30.P7molAFqPEpn4hwwEvKzYTEFHRlJhhvQ8GM29CqEDxk";

// We intentionally do NOT pass the auto-generated `Database` typing here.
// The auto-generated `types.ts` is empty (managed by Cloud, which sees a
// different/empty database) so importing it would make every `.from('table')`
// call fail with `never` typing errors. Without the generic, the SDK falls
// back to permissive `any`-like typings — runtime behaviour is unchanged.
//
// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
